export const ROUNDS = 16;
export const BLOCK_SIZE = 8; // bytes (64-bit block)
export const KEY_SIZE = 8; // bytes (64-bit key)

export class FeistelCipher {
  private subkeys: Uint32Array;

  constructor(key: Uint8Array) {
    if (key.length !== KEY_SIZE) {
      throw new Error(`key must be ${KEY_SIZE} bytes`);
    }
    this.subkeys = deriveSubkeys(key);
  }

  // Encrypt a single 64-bit block.
  //
  // Standard Feistel network with ROUNDS rounds:
  //   each round applies F to the right half and XORs the result into
  //   the left half, then swaps the halves.
  encryptBlock(block: Uint8Array): Uint8Array {
    let [l, r] = splitBlock(block);
    for (let i = 0; i < ROUNDS; i++) {
      const newR = (l ^ roundFn(r, this.subkeys[i])) >>> 0;
      l = r;
      r = newR;
    }
    return mergeHalves(l, r);
  }

  // Decrypt a single 64-bit block.
  //
  // F never needs to be invertible — apply subkeys in reverse order.
  decryptBlock(block: Uint8Array): Uint8Array {
    let [l, r] = splitBlock(block);
    for (let i = ROUNDS - 1; i >= 0; i--) {
      const newL = (r ^ roundFn(l, this.subkeys[i])) >>> 0;
      r = l;
      l = newL;
    }
    return mergeHalves(l, r);
  }
}

// ECB (Electronic Code Book) mode: each block encrypted independently.
// Suitable for demonstration; not semantically secure for real use.
export function encryptEcb(cipher: FeistelCipher, data: Uint8Array): Uint8Array {
  const padded = pkcs7Pad(data);
  const out = new Uint8Array(padded.length);
  for (let offset = 0; offset < padded.length; offset += BLOCK_SIZE) {
    const block = padded.slice(offset, offset + BLOCK_SIZE);
    out.set(cipher.encryptBlock(block), offset);
  }
  return out;
}

export function decryptEcb(cipher: FeistelCipher, data: Uint8Array): Uint8Array {
  if (data.length % BLOCK_SIZE !== 0) {
    throw new Error("ciphertext length not a multiple of block size");
  }
  const raw = new Uint8Array(data.length);
  for (let offset = 0; offset < data.length; offset += BLOCK_SIZE) {
    const block = data.slice(offset, offset + BLOCK_SIZE);
    raw.set(cipher.decryptBlock(block), offset);
  }
  return pkcs7Unpad(raw);
}

// Derive ROUNDS 32-bit subkeys from a 64-bit master key.
//
// The 64-bit key is split into two 32-bit words k0 and k1. A rotating
// state register is mixed with both words and a round constant to
// produce a distinct subkey for every round.
function deriveSubkeys(key: Uint8Array): Uint32Array {
  const k0 = readU32BE(key, 0);
  const k1 = readU32BE(key, 4);
  const subkeys = new Uint32Array(ROUNDS);
  let state = (k0 ^ k1) >>> 0;

  for (let i = 0; i < ROUNDS; i++) {
    state = ((state << 7) | (state >>> 25)) >>> 0;
    subkeys[i] = (k0 ^ k1 ^ state ^ (i * 0x6c078965)) >>> 0;
  }
  return subkeys;
}

// 256-byte substitution box — a bijection on bytes used by the round function.
// Generated by iterating x -> (x * 0x11 + 0x37) mod 256 until all values seen.
const SBOX: number[] = (() => {
  const box = new Array<number>(256);
  const seen = new Set<number>();
  for (let i = 0; i < 256; i++) {
    let x = (i * 0x11 + 0x37) & 0xff;
    while (seen.has(x)) {
      x = (x + 0x5b) & 0xff;
    }
    seen.add(x);
    box[i] = x;
  }
  return box;
})();

// The round function F — the only cipher-specific component.
//
// Unlike the Rust ARX mixer, this F uses byte-wise S-box substitution
// followed by a bit rotation and subkey XOR. Non-linear substitution
// is the classic alternative to multiply-add diffusion.
function roundFn(half: number, subkey: number): number {
  half = half >>> 0;
  subkey = subkey >>> 0;

  const b0 = SBOX[(half >>> 24) & 0xff];
  const b1 = SBOX[(half >>> 16) & 0xff];
  const b2 = SBOX[(half >>> 8) & 0xff];
  const b3 = SBOX[half & 0xff];

  let x = ((b0 << 24) | (b1 << 16) | (b2 << 8) | b3) >>> 0;
  x = ((x << 11) | (x >>> 21)) >>> 0;
  return (x ^ subkey ^ (subkey >>> 16)) >>> 0;
}

function readU32BE(bytes: Uint8Array, offset: number): number {
  return (
    ((bytes[offset] << 24) |
      (bytes[offset + 1] << 16) |
      (bytes[offset + 2] << 8) |
      bytes[offset + 3]) >>>
    0
  );
}

function writeU32BE(value: number, bytes: Uint8Array, offset: number): void {
  bytes[offset] = (value >>> 24) & 0xff;
  bytes[offset + 1] = (value >>> 16) & 0xff;
  bytes[offset + 2] = (value >>> 8) & 0xff;
  bytes[offset + 3] = value & 0xff;
}

// Split an 8-byte block into two 32-bit halves (big-endian).
function splitBlock(block: Uint8Array): [number, number] {
  return [readU32BE(block, 0), readU32BE(block, 4)];
}

// Recombine two 32-bit halves back into an 8-byte block.
function mergeHalves(l: number, r: number): Uint8Array {
  const block = new Uint8Array(BLOCK_SIZE);
  writeU32BE(l, block, 0);
  writeU32BE(r, block, 4);
  return block;
}

// PKCS#7 padding: append N bytes each with value N so the total length
// is a multiple of BLOCK_SIZE. When the input is already aligned a full
// block of padding is added so unpadding is always unambiguous.
function pkcs7Pad(data: Uint8Array): Uint8Array {
  const padLen = BLOCK_SIZE - (data.length % BLOCK_SIZE);
  const padded = new Uint8Array(data.length + padLen);
  padded.set(data);
  padded.fill(padLen, data.length);
  return padded;
}

function pkcs7Unpad(data: Uint8Array): Uint8Array {
  if (data.length === 0) {
    throw new Error("empty ciphertext");
  }
  const padByte = data[data.length - 1];
  const padLen = padByte;
  if (padLen === 0 || padLen > BLOCK_SIZE) {
    throw new Error("invalid padding");
  }
  const payloadLen = data.length - padLen;
  if (payloadLen < 0) {
    throw new Error("invalid padding");
  }
  for (let i = payloadLen; i < data.length; i++) {
    if (data[i] !== padByte) {
      throw new Error("invalid padding");
    }
  }
  return data.slice(0, payloadLen);
}
