export const ROUNDS = 16;
export const BLOCK_SIZE = 8; // bytes (64-bit block)
export const KEY_SIZE = 8; // bytes (64-bit key)

export class FeistelCipher {
  private subkeys: Uint32Array;

  constructor(key: Uint8Array) {
    if (key.length !== KEY_SIZE) {
      throw new Error(`key must be ${KEY_SIZE} bytes`);
    }
    this.subkeys = deriveSubkeys(key);
  }
}

// Derive ROUNDS 32-bit subkeys from a 64-bit master key.
//
// The 64-bit key is split into two 32-bit words k0 and k1. A rotating
// state register is mixed with both words and a round constant to
// produce a distinct subkey for every round.
function deriveSubkeys(key: Uint8Array): Uint32Array {
  const k0 = readU32BE(key, 0);
  const k1 = readU32BE(key, 4);
  const subkeys = new Uint32Array(ROUNDS);
  let state = (k0 ^ k1) >>> 0;

  for (let i = 0; i < ROUNDS; i++) {
    state = ((state << 7) | (state >>> 25)) >>> 0;
    subkeys[i] = (k0 ^ k1 ^ state ^ (i * 0x6c078965)) >>> 0;
  }
  return subkeys;
}

// 256-byte substitution box — a bijection on bytes used by the round function.
// Generated by iterating x -> (x * 0x11 + 0x37) mod 256 until all values seen.
const SBOX: number[] = (() => {
  const box = new Array<number>(256);
  const seen = new Set<number>();
  for (let i = 0; i < 256; i++) {
    let x = (i * 0x11 + 0x37) & 0xff;
    while (seen.has(x)) {
      x = (x + 0x5b) & 0xff;
    }
    seen.add(x);
    box[i] = x;
  }
  return box;
})();

// The round function F — the only cipher-specific component.
//
// Unlike the Rust ARX mixer, this F uses byte-wise S-box substitution
// followed by a bit rotation and subkey XOR. Non-linear substitution
// is the classic alternative to multiply-add diffusion.
function roundFn(half: number, subkey: number): number {
  half = half >>> 0;
  subkey = subkey >>> 0;

  const b0 = SBOX[(half >>> 24) & 0xff];
  const b1 = SBOX[(half >>> 16) & 0xff];
  const b2 = SBOX[(half >>> 8) & 0xff];
  const b3 = SBOX[half & 0xff];

  let x = ((b0 << 24) | (b1 << 16) | (b2 << 8) | b3) >>> 0;
  x = ((x << 11) | (x >>> 21)) >>> 0;
  return (x ^ subkey ^ (subkey >>> 16)) >>> 0;
}

function readU32BE(bytes: Uint8Array, offset: number): number {
  return (
    ((bytes[offset] << 24) |
      (bytes[offset + 1] << 16) |
      (bytes[offset + 2] << 8) |
      bytes[offset + 3]) >>>
    0
  );
}

function writeU32BE(value: number, bytes: Uint8Array, offset: number): void {
  bytes[offset] = (value >>> 24) & 0xff;
  bytes[offset + 1] = (value >>> 16) & 0xff;
  bytes[offset + 2] = (value >>> 8) & 0xff;
  bytes[offset + 3] = value & 0xff;
}

// Split an 8-byte block into two 32-bit halves (big-endian).
function splitBlock(block: Uint8Array): [number, number] {
  return [readU32BE(block, 0), readU32BE(block, 4)];
}

// Recombine two 32-bit halves back into an 8-byte block.
function mergeHalves(l: number, r: number): Uint8Array {
  const block = new Uint8Array(BLOCK_SIZE);
  writeU32BE(l, block, 0);
  writeU32BE(r, block, 4);
  return block;
}
